/**
 * Supabase Types - Stable Shim
 *
 * DO NOT EDIT this file except to add helper re-exports.
 * It re-exports the generated Database type from a stable path.
 *
 * The actual types are generated in supabase.generated.ts which is
 * overwritten by MCP tools. This shim provides a stable import path
 * for all application code.
 */

// Import for use in helper types
import type { Database } from "./supabase.generated";

// Re-export everything from the generated file
export type {
	CompositeTypes,
	Constants,
	Database,
	Enums,
	Json,
	Tables,
	TablesInsert,
	TablesUpdate,
} from "./supabase.generated";

export type Public = Database["public"];
export type AllTables = Public["Tables"];
export type Views = Public["Views"];
export type Functions = Public["Functions"];

// Helper types for common row operations (using non-conflicting names)
export type TableRow<T extends keyof AllTables> = AllTables[T]["Row"];
export type TableInsert<T extends keyof AllTables> = AllTables[T]["Insert"];
export type TableUpdate<T extends keyof AllTables> = AllTables[T]["Update"];
